### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by KlausMikhaelson** [KlausMikhaelson/wrestle-with-shapes#19]

**Comment by Layak-Ali** [comment]
Hey, is there any help i can do. I am searching to fix beginner issues and came across this post. I need some instructions on what to do and i hope i can help you with it.

**Comment by KlausMikhaelson** [comment]
Not looking for anything specific but would appreciate if you can improve the docs a bit and give it a star incase you like it !

**Comment by the-amazing-atharva** [comment]
I would like to be assigned to this issue !

**Comment by KlausMikhaelson** [comment]
sure ! @the-amazing-atharva
