### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'trim')

### ISSUE THREAD

**Issue by iONBain** [KlausMikhaelson/wrestle-with-shapes#27]
On screen load, the webapp is blank due to TypeError, checked in console
![image](https://user-images.githubusercontent.com/95289741/221199875-2aa84d50-5bdf-49f2-b686-89ee25a51c08.png)

**Comment by KlausMikhaelson** [comment]
Hey @iONBain thanks for making this issue I had no idea about it, you definitely can work on it and lmk if you need any help !

**Comment by iONBain** [comment]
Hi @KlausMikhaelson , I have created a PR, pls check if everything looks good.

**Comment by KlausMikhaelson** [comment]
Hey @iONBain ig it was a problem with render and not a real issue since it's working perfectly now or can you show me when you were getting this error ?
Thank you !

**Comment by iONBain** [comment]
seems working good! apologies for late reply, been stuck in some work :)
